### ISSUE TITLE
NameError

### ISSUE THREAD

**Issue by gh-cguzman** [BGSpiegl/GCparagon#10]
Looks like the new version causes an issue after installation:

```
Traceback (most recent call last):
  File "/stormhome/carlos/micromamba/envs/GCparagon/bin/gcparagon", line 5, in <module>
    from GCparagon.correct_GC_bias import main
  File "/stormhome/carlos/micromamba/envs/GCparagon/lib/python3.10/site-packages/GCparagon/correct_GC_bias.py", line 1898, in <module>
    default_weight: float = 1.0, tag_name=DEFAULT_TAG_NAME,
NameError: name 'DEFAULT_TAG_NAME' is not defined. Did you mean: 'DEFAULT_GC_TAG_NAME'?
```

**Comment by gh-cguzman** [comment]
My temporary fix was to simply rename all `DEFAULT_TAG_NAME` variables to `DEFAULT_GC_TAG_NAME`.

**Comment by BGSpiegl** [comment]
Thank you! Solved in commit a2cb974a
