### ISSUE TITLE
In orden_bams: "ValueError: invalid literal for int() with base 10: 'A*01:02'"

### ISSUE THREAD

**Issue by Rociocc93** [BGSpiegl/GCparagon#13]
Hi!

I am trying to run GCparagon on sWGS samples aligned using the `nf-core/sarek pipeline`. I have generated the 2bit reference file from the fasta file originally used in the pipeline. For the gc content distribution table and the intervals bed files, I've kept the default ones. GCparagon runs smoothly up to the bam tagging part, where I get the following error:

```
2024-09-10 16:42:19,354 - GCparagon - ERROR - The following exception occurred when trying to process BAM file /path/to/file/SampleName.bam:
Traceback (most recent call last):
  File "/home/-/anaconda3/envs/GCparagon/bin/gcparagon", line 8, in <module>
    sys.exit(main())
  File "/home/-/anaconda3/envs/GCparagon/lib/python3.10/site-packages/GCparagon/correct_GC_bias.py", line 3263, in main
    tag_bam_with_correction_weights_parallel(
  File "/home/-/anaconda3/envs/GCparagon/lib/python3.10/site-packages/GCparagon/correct_GC_bias.py", line 2345, in tag_bam_with_correction_weights_parallel
    tagged_scaffold_bam_files_in_order = order_bams(bam_list=tagged_scaffold_bam_files)
  File "/home/-/anaconda3/envs/GCparagon/lib/python3.10/site-packages/GCparagon/correct_GC_bias.py", line 2205, in order_bams
    bam_paths_with_locus.append(((chrm, int(strt)), str(bam_nm)))
ValueError: invalid literal for int() with base 10: 'A*01:02'
Continuing to process next BAM file..
```

By checking the temporary directory, I can see that the tagged chunked 50MB bam files have been correctly generated. The issue seems to come from the `order_bams` function in the `correct_GC_bias.py ` script, since I have multiple GCcorr.bam files named like this `SampleName+HLA-C*08:41-0-3019.GCcorr`, and the function is using "-" to split chr, start, and stop.

I think that just excluding HLA, alt, decoy and random chunks would be fine, since I don't need those for downstream analyses. Do you think that could be safely implemented? I just wanted to check with you before trying to implement it myself, since this could also be helpful for other users, and I don't want to break any other possible dependant code chunks in the pipeline.

Thanks in advance,

Rocío

**Comment by BGSpiegl** [comment]
Hi Rocio,

Thank you for submitting this and sorry for the troubles.
I will have a look tomorrow and try to reproduce the error + fix the implementation since (I think) there was already another user who had a similar BAM file name dependent problem.

BR Benjamin

**Comment by BGSpiegl** [comment]
Hello again,

I tested the curernt version of GCparagon (v0.6.10) with a BAM file called `P244_6+HLA-C*08:41-0-3019.bam`. There was no problem in creating the GC-tagged version. Also the many scaffold BAM files were created. Which version are you using? If you are using an older version, please update to the newest version (probably using the singularity container which you can pull from cloud.sylabs.io as described in more detail now [here](https://github.com/BGSpiegl/GCparagon?tab=readme-ov-file#singularity-container)).
![Screenshot from 2024-09-11 15-49-26](https://github.com/user-attachments/assets/f92e6693-1588-4194-aa7a-a9b43d0653c2)

Please give some feedback if your problem is still existing in the newest version!
If you have a specific file naming for which the error arises, please supply the exact name of your input file such that I can reproduce and correct the erroneous behavior of the program.

**Comment by Rociocc93** [comment]
Hi,

Sorry for my late reply, yesterday was bank holiday here! 

I was running version 0.6.7, which I installed a couple of weeks ago I think. I have created a new conda environment with the latest version, but unfortunately I found the same error as before:

```
 2024-09-12 09:34:49,332 - GCparagon - ERROR - The following exception occurred when trying to process BAM file /path/to/file/XX_SAMPLEID.md.bam:
Traceback (most recent call last):
  File "/home/username/Software/GCparagon_0.6.10/GCparagon/src/GCparagon/correct_GC_bias.py", line 3310, in <module>
    sys.exit(main())
  File "/home/username/Software/GCparagon_0.6.10/GCparagon/src/GCparagon/correct_GC_bias.py", line 3264, in main
    tag_bam_with_correction_weights_parallel(
  File "/home/username/Software/GCparagon_0.6.10/GCparagon/src/GCparagon/correct_GC_bias.py", line 2345, in tag_bam_with_correction_weights_parallel
    tagged_scaffold_bam_files_in_order = order_bams(bam_list=tagged_scaffold_bam_files)
  File "/home/username/Software/GCparagon_0.6.10/GCparagon/src/GCparagon/correct_GC_bias.py", line 2205, in order_bams
    bam_paths_with_locus.append(((chrm, int(strt)), str(bam_nm)))
ValueError: invalid literal for int() with base 10: 'A*01:02'
Continuing to process next BAM file..
```

The filename of the analysed bam file is *XX_SAMPLEID.md.bam*, and the scaffold bam file where the script is first raising the error has this exact structure: *XX_SAMPLEID.md+HLA-A\*01:02-0-3374.GCcorr.bam*. My understanding is that the `order_bams` function is taking HLA as the chromosome name and then A*01:02 as the start position, which cannot be converted to `int`. I guess the only difference with your test is that by taking the last item after the + sign, you are still getting a chr1-0-10000 structure, whereas I am not.

Quick fixes I can think of: either adding a conditional to only include in the `bam_paths_with_locus` list those scaffold bam files that are compliant with the chr-start-stop assumption, or using regex (something like `([A-Za-z0-9\*:_]+)-(\d+)-(\d+)`) that work with alternative patterns.

Thanks again,

Rocio

**Comment by BGSpiegl** [comment]
As I cannot reproduce the behavior that you are describing using a human sample (GRCh38 analysis set reference genome), the following must hold true for the output to be created as you stated:

If your input BAM file is named `XX_SAMPLEID.md.bam` but the files written to the temporary directory are named like `XX_SAMPLEID.md+HLA-A*01:02-0-3374.GCcorr.bam`, this suggests that your "chromosome" string would be `HLA-A*01:02`.
In this case, a different separator and regex should be used to securely isolate contig/scaffold information and start/stop information from the file names. To be honest, I didn't expect exotic contig/scaffold names to be used when I wrote this piece of the code.

I never encountered such a contig before but it is good to know that there are other applications where people use GCparagon apart from the standard human chromosomes (i.e., analysis of ALT contigs).
I will release the update in a new version v0.6.11 soon!

**Comment by BGSpiegl** [comment]
My commit b9c922984181384a269817f895c63b07ea03c1ff should have taken care of the problem. The latest version is now v0.6.11 which should have maximum robustness regarding BAM file naming and contig naming of the reference genome.

(even if a BAM file is creatively named `P.GCcorr.bam.GCtagged.bam-1_+GcPaRa+2-GcPaRa-+GcPaRa+chrHLA*02:13-GcPaRa-0-GcPaRa-50000.GCcorr.bam`, GCparagon still finishes without problem)

Please test the new version and give feedback if your problem has been fixed!

**Comment by Rociocc93** [comment]
Hello,

That's wonderful! I've just tested it and everything is working smoothly. 

Thanks again for your quick handling of the issue! 

R.
