### ISSUE TITLE
ERROR: Too many open files

### ISSUE THREAD

**Issue by gh-cguzman** [BGSpiegl/GCparagon#8]
```
| 2024-05-21 17:56:56,181 - GCparagon - INFO - Successfully reduced the AES reconstruction error of the genomic GC content from 0.187 to 0.127 (took 965.89 ms).
[E::hts_idx_load3] Could not load local index file 'bams/B0277_0pt25X_S71.bam.bai' : Too many open files
[E::hts_open_format] Failed to open file "bams/B0277_0pt25X_S71.bam" : Too many open files
CRITICAL - an unexpected error occurred:
    -->> ''
[E::hts_idx_load3] Could not load local index file 'bams/B0277_0pt25X_S71.bam.bai' : Too many open files
[E::hts_open_format] Failed to open file "bams/B0277_0pt25X_S71.bam" : Too many open files
CRITICAL - an unexpected error occurred:
    -->> ''
| 2024-05-21 18:05:25,408 - GCparagon - ERROR - At least one GC bias worker process failed during processing of BAM file bams/B0277_0pt25X_S71.bam:
Traceback (most recent call last):
  File "/home/carlos/micromamba/envs/GCparagon/bin/gcparagon", line 8, in <module>
    sys.exit(main())
  File "/home/carlos/micromamba/envs/GCparagon/lib/python3.10/site-packages/GCparagon/correct_GC_bias.py", line 3210, in main
    (mask_path, weights_mask)) = compute_gc_bias_parallel(
  File "/home/carlos/micromamba/envs/GCparagon/lib/python3.10/site-packages/GCparagon/correct_GC_bias.py", line 1497, in compute_gc_bias_parallel
    raise ChildProcessError(f"{sum([rcv_dt is None for rcv_dt in received_data]):,} GC bias worker process(es) "
ChildProcessError: 2 GC bias worker process(es) failed!
```

Command used:
```
gcparagon --bam bams/B0277_0pt25X_S71.bam --output-bam -rgb hg19 --temporary-directory tmp_gcparagon/ -mafl 200 -mifl 100
```

Odd little error happening. Any idea what the issue might be? There should be plenty of space, and RAM.

Thanks!

**Comment by gh-cguzman** [comment]
Fixed by increasing the number of files that a process can open using:

```
ulimit -Sn 4096
```

Sorry! :)

**Comment by BGSpiegl** [comment]
The `too many open files` problem of your last issue is caused by pyranges which should be fixed in the future (the current version on github already contains the fix)
https://github.com/pyranges/pyranges/issues/377
